import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import dotenv from "dotenv";
dotenv.config();
import fs from "fs";
import path from "path";


const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const copy_files_plugin = {
	name: 'copy_files',
	setup(build) {
		build.onEnd(() => {
			// Ensure build directory exists
			const buildDir = "./build";
			if (!fs.existsSync(buildDir)) {
				fs.mkdirSync(buildDir, { recursive: true });
			}
			
			// Copy required files to build directory
			fs.copyFileSync("./manifest.json", path.join(buildDir, "manifest.json"));
			fs.copyFileSync("./styles.css", path.join(buildDir, "styles.css"));
			fs.copyFileSync("./versions.json", path.join(buildDir, "versions.json"));
			
			// Copy to Obsidian plugins folder if path is set
			if (process.env.OBSIDIAN_PLUGINS_PATH) {
				const plugin_path = path.join(process.env.OBSIDIAN_PLUGINS_PATH, "smart-memos");
				
				if (!fs.existsSync(plugin_path)) {
					fs.mkdirSync(plugin_path, { recursive: true });
				}
				
				fs.copyFileSync(path.join(buildDir, "main.js"), path.join(plugin_path, "main.js"));
				fs.copyFileSync(path.join(buildDir, "manifest.json"), path.join(plugin_path, "manifest.json"));
				fs.copyFileSync(path.join(buildDir, "styles.css"), path.join(plugin_path, "styles.css"));
				fs.copyFileSync(path.join(buildDir, "versions.json"), path.join(plugin_path, "versions.json"));
				// add empty .hotreload file
				fs.writeFileSync(path.join(plugin_path, ".hotreload"), "");
				
				console.log("Plugin built to ./build/ and copied to obsidian plugins folder");
			} else {
				console.log("Plugin built to ./build/ folder");
			}
		});
	}
};
const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: "inline",
	treeShaking: true,
	outfile: "build/main.js",
	plugins: [
		copy_files_plugin
	]
});
if(!prod) await context.watch();
else {
	await context.rebuild();
	process.exit(0);
}

