import { Notice } from 'obsidian';
import { AIProvider, AIProviderSettings, GenerationOptions } from './AIProvider';

export class GeminiProvider extends AIProvider {
    private audioContext: AudioContext;
    
    constructor(settings: AIProviderSettings, audioContext: AudioContext) {
        super(settings);
        this.audioContext = audioContext;
    }
    
    getName(): string {
        return 'Google Gemini';
    }
    
    async transcribe(audioBuffer: ArrayBuffer, audioContext: AudioContext): Promise<string> {
        if (!this.settings.apiKey || this.settings.apiKey.length <= 1) {
            throw new Error('Google Gemini API Key is not provided.');
        }
        
        try {
            // Convert ArrayBuffer to base64 for Gemini API
            const base64Audio = this.arrayBufferToBase64(audioBuffer);
            
            const requestBody = {
                contents: [
                    {
                        parts: [
                            {
                                text: "Please transcribe this audio file accurately. Provide only the transcription text without any additional commentary."
                            },
                            {
                                inline_data: {
                                    mime_type: "audio/wav",
                                    data: base64Audio
                                }
                            }
                        ]
                    }
                ],
                generationConfig: {
                    temperature: 0.1,
                    topK: 1,
                    topP: 0.8,
                    maxOutputTokens: 8192,
                }
            };
            
            const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${this.settings.model}:generateContent?key=${this.settings.apiKey}`, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify(requestBody)
            });
            
            if (!response.ok) {
                const errorData = await response.json();
                throw new Error(`Gemini API error: ${errorData.error?.message || response.statusText}`);
            }
            
            const data = await response.json();
            
            if (!data.candidates || data.candidates.length === 0) {
                throw new Error('No transcription generated by Gemini');
            }
            
            const transcription = data.candidates[0].content?.parts?.[0]?.text;
            if (!transcription) {
                throw new Error('Empty transcription from Gemini');
            }
            
            return transcription.trim();
            
        } catch (error: any) {
            console.error('Gemini transcription failed:', error);
            if (error.message.includes('403')) {
                throw new Error('Gemini API key is invalid or insufficient permissions.');
            } else if (error.message.includes('400')) {
                throw new Error('Invalid request format for Gemini API.');
            } else if (error.message.includes('429')) {
                throw new Error('Gemini API rate limit exceeded. Please try again later.');
            } else {
                throw error;
            }
        }
    }
    
    async generateText(options: GenerationOptions): Promise<string> {
        if (!this.settings.apiKey || this.settings.apiKey.length <= 1) {
            throw new Error('Google Gemini API Key is not provided.');
        }
        
        try {
            const requestBody = {
                contents: [
                    {
                        parts: [
                            {
                                text: options.messages[options.messages.length - 1].content
                            }
                        ]
                    }
                ],
                generationConfig: {
                    temperature: 0.7,
                    topK: 40,
                    topP: 0.95,
                    maxOutputTokens: 8192,
                }
            };
            
            const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${this.settings.model}:streamGenerateContent?key=${this.settings.apiKey}`, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify(requestBody)
            });
            
            if (!response.ok) {
                const errorData = await response.json();
                throw new Error(`Gemini API error: ${errorData.error?.message || response.statusText}`);
            }
            
            const reader = response.body?.getReader();
            if (!reader) {
                throw new Error('Response body is not readable');
            }
            
            const decoder = new TextDecoder();
            let fullText = '';
            let buffer = '';
            
            while (true) {
                const { done, value } = await reader.read();
                if (done) break;
                
                buffer += decoder.decode(value, { stream: true });
                const lines = buffer.split('\n');
                buffer = lines.pop() || '';
                
                for (const line of lines) {
                    if (line.trim() && !line.trim().startsWith('[') && !line.trim().startsWith(']')) {
                        try {
                            const json = JSON.parse(line);
                            const content = json.candidates?.[0]?.content?.parts?.[0]?.text;
                            
                            if (content) {
                                fullText += content;
                                if (options.onChunk) {
                                    options.onChunk(content);
                                }
                            }
                        } catch (e) {
                            // Skip malformed JSON lines
                            console.debug('Skipping malformed JSON:', line);
                        }
                    }
                }
            }
            
            if (options.onComplete) {
                options.onComplete(fullText);
            }
            return fullText;
            
        } catch (error: any) {
            console.error('Gemini generation failed:', error);
            throw error;
        }
    }
    
    async getAvailableModels(): Promise<string[]> {
        return [
            'gemini-2.0-flash-exp',
            'gemini-2.0-flash-thinking-exp-1219',
            'gemini-1.5-pro',
            'gemini-1.5-flash',
            'gemini-1.5-flash-8b'
        ];
    }
    
    async validateSettings(): Promise<boolean> {
        if (!this.settings.apiKey || this.settings.apiKey.length <= 1) {
            return false;
        }
        
        try {
            const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models?key=${this.settings.apiKey}`);
            return response.ok;
        } catch {
            return false;
        }
    }
    
    private arrayBufferToBase64(buffer: ArrayBuffer): string {
        const bytes = new Uint8Array(buffer);
        let binary = '';
        for (let i = 0; i < bytes.byteLength; i++) {
            binary += String.fromCharCode(bytes[i]);
        }
        return btoa(binary);
    }
}